In [28]:
from pathlib import Path

import pandas as pd

In [29]:
df = pd.read_csv(
    Path("").absolute() / "data" / "transformed" / "repos.csv", index_col="full_name"
)

In [30]:
df.sort_values("stargazers_count", ascending=False)[["stargazers_count"]].head(10)

                                 stargazers_count
full_name
ftlabs/fastclick                            18601
fivethirtyeight/data                        17136
bloomberg/memray                            14235
NUKnightLab/TimelineJS                       8927
nytimes/covid-19-data                        6995
newsapps/beeswithmachineguns                 6598
wireservice/csvkit                           6231
guardian/frontend                            5867
nytimes/objective-c-style-guide              5840
GoogleTrends/data                            4712

In [26]:
df.sort_values("forks_count", ascending=False)[["forks_count"]].head(10)

                                 forks_count
full_name
fivethirtyeight/data                   11132
nytimes/covid-19-data                   3437
ftlabs/fastclick                        3195
NUKnightLab/TimelineJS                  1551
nytimes/objective-c-style-guide         1253
bloomberg/bbit-learning-labs             972
freedomofpress/securedrop                702
NUKnightLab/TimelineJS3                  639
newsapps/beeswithmachineguns             630
wireservice/csvkit                       615